import React from 'react';
import { Helmet } from 'react-helmet';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import Header from '@/components/Header.jsx';
import Footer from '@/components/Footer.jsx';
import BreadcrumbNav from '@/components/BreadcrumbNav.jsx';
import PricingTierCard from '@/components/PricingTierCard.jsx';
import { Button } from '@/components/ui/button.jsx';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion.jsx';
import { useLanguage } from '@/contexts/LanguageContext.jsx';

export default function AIDrivenMarketingPricingPage() {
  const { lang, lp } = useLanguage();
  const T = (en, ms) => (lang === 'ms' ? ms : en);

  const TIERS = [
    {
      name: T('AI Audit & Setup', 'Audit & Persediaan AI'),
      price: "RM 5,000",
      numericPrice: 5000,
      description: T('One-time implementation of AI tools into your workflow.', 'Pelaksanaan sekali sahaja alat AI ke dalam aliran kerja anda.'),
      features: [
        T('Marketing Workflow Audit', 'Audit Aliran Kerja Pemasaran'),
        T('AI Tool Stack Recommendations', 'Cadangan Set Alat AI'),
        T('Custom ChatGPT Prompt Library', 'Perpustakaan Prompt ChatGPT Tersuai'),
        T('Basic Automation Setup (Zapier)', 'Persediaan Automasi Asas (Zapier)'),
        T('Team Training Session (2 Hours)', 'Sesi Latihan Pasukan (2 Jam)'),
        T('30 Days Post-Setup Support', 'Sokongan 30 Hari Selepas Persediaan'),
      ],
      isPopular: false
    },
    {
      name: T('AI Content Engine', 'Enjin Kandungan AI'),
      price: T('RM 4,500/mo', 'RM 4,500/bln'),
      numericPrice: 4500,
      description: T('Ongoing AI-powered content generation and optimization.', 'Penjanaan dan pengoptimuman kandungan berkuasa AI yang berterusan.'),
      features: [
        T('AI-Generated Blog Posts (8/mo)', 'Catatan Blog Jana AI (8/bln)'),
        T('Programmatic SEO Implementation', 'Pelaksanaan SEO Programatik'),
        T('Dynamic Email Copywriting', 'Penulisan Salinan E-mel Dinamik'),
        T('Predictive Ad Copy Testing', 'Ujian Salinan Iklan Ramalan'),
        T('Automated Social Scheduling', 'Penjadualan Sosial Automatik'),
        T('Monthly AI Performance Review', 'Semakan Prestasi AI Bulanan'),
        T('Continuous Prompt Optimization', 'Pengoptimuman Prompt Berterusan'),
      ],
      isPopular: true
    },
    {
      name: T('Enterprise AI', 'AI Perusahaan'),
      price: "Custom",
      description: T('Custom AI models trained on your proprietary data.', 'Model AI tersuai yang dilatih pada data proprietari anda.'),
      features: [
        T('Custom LLM Fine-tuning', 'Penalaan Halus LLM Tersuai'),
        T('Proprietary Data Integration', 'Integrasi Data Proprietari'),
        T('Predictive Customer Analytics', 'Analitik Pelanggan Ramalan'),
        T('Automated Personalization Engine', 'Enjin Pemperibadian Automatik'),
        T('API Development & Integration', 'Pembangunan & Integrasi API'),
        T('Dedicated AI Engineer', 'Jurutera AI Khusus'),
        T('Enterprise-grade Security', 'Keselamatan Gred Perusahaan'),
      ],
      isPopular: false,
      isCustom: true
    }
  ];

  const FAQS = [
    {
      q: T('Will AI replace my marketing team?', 'Adakah AI akan menggantikan pasukan pemasaran saya?'),
      a: T('No, our AI solutions are designed to augment and empower your team, automating repetitive tasks so they can focus on high-level strategy and creativity.', 'Tidak, penyelesaian AI kami direka untuk menambah dan memperkasakan pasukan anda, mengautomasi tugas berulang supaya mereka boleh fokus pada strategi peringkat tinggi dan kreativiti.')
    },
    {
      q: T('Is the content generated by AI safe for SEO?', 'Adakah kandungan yang dijana AI selamat untuk SEO?'),
      a: T("Yes. We use AI to assist in drafting, but all content is heavily edited, fact-checked, and humanized by our experts to ensure it meets Google's helpful content guidelines.", 'Ya. Kami menggunakan AI untuk membantu merangka, tetapi semua kandungan disunting rapi, disemak fakta, dan dimanusiakan oleh pakar kami untuk memastikan ia memenuhi garis panduan kandungan berguna Google.')
    },
    {
      q: T('What tools do you use?', 'Alat apa yang anda gunakan?'),
      a: T('We utilize a custom stack including OpenAI (ChatGPT), Anthropic, Midjourney, Zapier, Make, and proprietary scripts depending on your specific needs.', 'Kami menggunakan set tersuai termasuk OpenAI (ChatGPT), Anthropic, Midjourney, Zapier, Make, dan skrip proprietari bergantung pada keperluan khusus anda.')
    }
  ];

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Helmet>
        <title>{T('AI-Driven Marketing Pricing | BrandKraf', 'Harga Pemasaran Dipacu AI | BrandKraf')}</title>
        <meta name="description" content={T('Transparent pricing for AI marketing automation and implementation.', 'Harga telus untuk automasi dan pelaksanaan pemasaran AI.')} />
      </Helmet>

      <Header />

      <main className="flex-grow pt-32 pb-24">
        <div className="container-custom">
          <BreadcrumbNav currentService={T('AI-Driven Marketing', 'Pemasaran Dipacu AI')} />

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-3xl mb-16"
          >
            <h1 className="mb-6">{T('AI-Driven Marketing Pricing', 'Harga Pemasaran Dipacu AI')}</h1>
            <p className="text-xl text-muted-foreground">
              {T(
                'Scale your output and efficiency with cutting-edge AI implementation. We build the systems that give you an unfair advantage.',
                'Kembangkan output dan kecekapan anda dengan pelaksanaan AI terkini. Kami membina sistem yang memberi anda kelebihan luar biasa.',
              )}
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-24">
            {TIERS.map((tier, idx) => (
              <PricingTierCard
                key={idx}
                {...tier}
                delay={idx * 0.1}
                serviceCategory="AI-Driven Marketing"
              />
            ))}
          </div>

          <div className="max-w-3xl mx-auto mb-24">
            <h2 className="text-center mb-12">{T('Frequently Asked Questions', 'Soalan Lazim')}</h2>
            <Accordion type="single" collapsible className="w-full">
              {FAQS.map((faq, idx) => (
                <AccordionItem key={idx} value={`faq-${idx}`}>
                  <AccordionTrigger className="text-left font-semibold text-lg">{faq.q}</AccordionTrigger>
                  <AccordionContent className="text-muted-foreground text-base">
                    {faq.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>

          <div className="text-center">
            <Button variant="outline" size="lg" asChild>
              <Link to={lp('/pricing')}><ArrowLeft className="mr-2 w-4 h-4" /> {T('Back to All Services', 'Kembali ke Semua Perkhidmatan')}</Link>
            </Button>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}