import React from 'react';
import { Helmet } from 'react-helmet';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import Header from '@/components/Header.jsx';
import Footer from '@/components/Footer.jsx';
import BreadcrumbNav from '@/components/BreadcrumbNav.jsx';
import PricingTierCard from '@/components/PricingTierCard.jsx';
import { Button } from '@/components/ui/button.jsx';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion.jsx';

const TIERS = [
  {
    name: "AI Audit & Setup",
    price: "RM 5,000",
    numericPrice: 5000,
    description: "One-time implementation of AI tools into your workflow.",
    features: [
      "Marketing Workflow Audit",
      "AI Tool Stack Recommendations",
      "Custom ChatGPT Prompt Library",
      "Basic Automation Setup (Zapier)",
      "Team Training Session (2 Hours)",
      "30 Days Post-Setup Support"
    ],
    isPopular: false
  },
  {
    name: "AI Content Engine",
    price: "RM 4,500/mo",
    numericPrice: 4500,
    description: "Ongoing AI-powered content generation and optimization.",
    features: [
      "AI-Generated Blog Posts (8/mo)",
      "Programmatic SEO Implementation",
      "Dynamic Email Copywriting",
      "Predictive Ad Copy Testing",
      "Automated Social Scheduling",
      "Monthly AI Performance Review",
      "Continuous Prompt Optimization"
    ],
    isPopular: true
  },
  {
    name: "Enterprise AI",
    price: "Custom",
    description: "Custom AI models trained on your proprietary data.",
    features: [
      "Custom LLM Fine-tuning",
      "Proprietary Data Integration",
      "Predictive Customer Analytics",
      "Automated Personalization Engine",
      "API Development & Integration",
      "Dedicated AI Engineer",
      "Enterprise-grade Security"
    ],
    isPopular: false,
    isCustom: true
  }
];

const FAQS = [
  {
    q: "Will AI replace my marketing team?",
    a: "No, our AI solutions are designed to augment and empower your team, automating repetitive tasks so they can focus on high-level strategy and creativity."
  },
  {
    q: "Is the content generated by AI safe for SEO?",
    a: "Yes. We use AI to assist in drafting, but all content is heavily edited, fact-checked, and humanized by our experts to ensure it meets Google's helpful content guidelines."
  },
  {
    q: "What tools do you use?",
    a: "We utilize a custom stack including OpenAI (ChatGPT), Anthropic, Midjourney, Zapier, Make, and proprietary scripts depending on your specific needs."
  }
];

export default function AIDrivenMarketingPricingPage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Helmet>
        <title>AI-Driven Marketing Pricing | BrandKraf</title>
        <meta name="description" content="Transparent pricing for AI marketing automation and implementation." />
      </Helmet>

      <Header />

      <main className="flex-grow pt-32 pb-24">
        <div className="container-custom">
          <BreadcrumbNav currentService="AI-Driven Marketing" />
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-3xl mb-16"
          >
            <h1 className="mb-6">AI-Driven Marketing Pricing</h1>
            <p className="text-xl text-muted-foreground">
              Scale your output and efficiency with cutting-edge AI implementation. We build the systems that give you an unfair advantage.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-24">
            {TIERS.map((tier, idx) => (
              <PricingTierCard 
                key={idx} 
                {...tier} 
                delay={idx * 0.1} 
                serviceCategory="AI-Driven Marketing"
              />
            ))}
          </div>

          <div className="max-w-3xl mx-auto mb-24">
            <h2 className="text-center mb-12">Frequently Asked Questions</h2>
            <Accordion type="single" collapsible className="w-full">
              {FAQS.map((faq, idx) => (
                <AccordionItem key={idx} value={`faq-${idx}`}>
                  <AccordionTrigger className="text-left font-semibold text-lg">{faq.q}</AccordionTrigger>
                  <AccordionContent className="text-muted-foreground text-base">
                    {faq.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>

          <div className="text-center">
            <Button variant="outline" size="lg" asChild>
              <Link to="/pricing"><ArrowLeft className="mr-2 w-4 h-4" /> Back to All Services</Link>
            </Button>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}